### ISSUE TITLE
Build fails when .babelrc for Babel 6 present

### ISSUE THREAD

**Issue by rkclark** [Financial-Times/origami-build-tools#412]
Hi,

I'm using OBT in a project that uses Babel 6 for transpiling test files. I'm getting a very awkward issue to the presence of the .babelrc file in my project root that is required for Babel 6. I believe it is causing the Babel 5 running in OBT to fail.

Here is my npm script for running my tests:

`    "test": "NODE_ENV=test ./node_modules/.bin/wdio wdio.conf.js && mocha test/server --require babel-core/register"
`

This script requires a .babelrc file to be present in the project root with this content:

```
{
  "presets": ["es2015"]
}
```

At the same time, I have OBT set up that runs from a gulpfile as follows:
```
gulp.task('build', function() {
	return obt.build(gulp, {
		js: './src/client/js/main.js',
		sass: './src/client/scss/main.scss',
		buildJs: 'bundle.js',
		buildCss: 'bundle.css',
		buildFolder: 'src/public'
	});
});
```

If I run the gulp build command, I get the following Babel error:

```[12:03:58] 'build' errored after 1.09 s
[12:03:58] Error in plugin 'webpack-stream'
Message:
    ModuleBuildError: Module build failed: ReferenceError: [BABEL] /home/rick/web/ft-news-app/src/client/js/main.js: Unknown option: /home/rick/web/ft-news-app/.babelrc.presets
    at Logger.error (/home/rick/web/ft-news-app/node_modules/origami-build-tools/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/home/rick/web/ft-news-app/node_modules/origami-build-tools/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/home/rick/web/ft-news-app/node_modules/origami-build-tools/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/rick/web/ft-news-app/node_modules/origami-build-tools/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/rick/web/ft-news-app/node_modules/origami-build-tools/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/rick/web/ft-news-app/node_modules/origami-build-tools/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/rick/web/ft-news-app/node_modules/origami-build-tools/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/rick/web/ft-news-app/node_modules/origami-build-tools/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/home/rick/web/ft-news-app/node_modules/origami-build-tools/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/rick/web/ft-news-app/node_modules/origami-build-tools/node_modules/babel-loader/index.js:71:12)
```

It appears that the Babel 5 running in OBT is getting thrown by the `presets` option, which makes sense, its its a Babel 6 requirement not a Babel 5 one.

**Now here's the kicker!** If I remove the .babelrc file from the project root then the OBT build command in the gulpfile works without error and my build completes. However, my test script will then error instead as Babel 6 will fail to transpile.

So at any one time, I can either have my tests or my build working, by adding or removing the .babelrc. This is not ideal! Have you encountered this problem before and do you have any suggestions?

Thanks

Rick

**Comment by rkclark** [comment]
I found a hacky temporary solution...

I added two new tasks to my gulpfile. This one runs before the build task:

```
gulp.task('stopBabelrc', function(){
	gulp.src('.babelrc')
		.pipe(rename('.voidbabelrc'))
		.pipe(gulp.dest('./'));
	del(['./.babelrc']);
});
```

And this one runs after:

```
gulp.task('startBabelrc', function(){
	gulp.src('.voidbabelrc')
		.pipe(rename('.babelrc'))
		.pipe(gulp.dest('./'));;
	del(['./.voidbabelrc']);
});
```

So basically, .babelrc is temporarily renamed, allowing the build task to complete. Once it is completed, .babelrc is given its correct name back.

Ok as temporary bandage I suppose, but would still like to find a real solution! :)

**Comment by JakeChampion** [comment]
This has been resolved in origami-build-tools version 7 👍 . We now use the babel presets for 2015, 2016 and 2017 ecmascript
